### ISSUE TITLE
Agda path in preferences

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#3]
1. In the preferences, the file browser for Agda path does not allow me to select the agda executable (it's greyed out).
2. The input field for Agda path does not seem to accept Paste (⌘V) instead the paste went into the main editing window.

**Comment by markokoleznik** [comment]
1. My bad. Now Browse window also shows hidden folders (Library folder is otherwise hidden in my case). Any thoughts? Will users be angry about invading their privacy? :)
2. Fixed in https://github.com/markokoleznik/agda-writer/commit/d21ee00ffd50c817f92b15fbc3a1c6807faf78b1.

Can I close the issue?

**Comment by andrejbauer** [comment]
Yes, I think this is closable.
